# Generated by Django 2.2.13 on 2020-09-02 21:09

import crmapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofservices', models.IntegerField(default=1, verbose_name='No Of Services')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100, null=True, verbose_name='Customer Name')),
                ('cr', models.IntegerField(blank=True, null=True, unique=True)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('branches', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_services', models.CharField(blank=True, max_length=1000)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customers', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='customercontactnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customercontactnumbername', models.CharField(max_length=100, null=True, verbose_name='Customer Contact No')),
                ('mobile1', models.IntegerField(blank=True, null=True)),
                ('mobile2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Contact Numbers',
                'verbose_name': 'Customer Contact Number',
            },
        ),
        migrations.CreateModel(
            name='dealcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealcategoryname', models.CharField(max_length=100, null=True, verbose_name='Deal Category Name')),
            ],
            options={
                'verbose_name_plural': 'Deal Categorys',
                'verbose_name': 'Deal Category',
            },
        ),
        migrations.CreateModel(
            name='employeestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeestatusname', models.CharField(max_length=100, null=True, verbose_name='Employee Status')),
            ],
            options={
                'verbose_name_plural': 'Employee Status',
                'verbose_name': 'Employee  Status',
            },
        ),
        migrations.CreateModel(
            name='jobtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitlename', models.CharField(max_length=100, null=True, verbose_name='Job Title')),
            ],
            options={
                'verbose_name_plural': 'Job Titles',
                'verbose_name': 'Job Title',
            },
        ),
        migrations.CreateModel(
            name='leadsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadsourcename', models.CharField(max_length=100, null=True, verbose_name='Lead Source')),
            ],
            options={
                'verbose_name_plural': 'Lead Source',
                'verbose_name': 'Lead Source',
            },
        ),
        migrations.CreateModel(
            name='operationstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationstatusname', models.CharField(max_length=100, null=True, verbose_name='Operation_Status')),
            ],
            options={
                'verbose_name_plural': 'Operation Status',
                'verbose_name': 'Operation Status',
            },
        ),
        migrations.CreateModel(
            name='opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms', models.IntegerField(unique=True, verbose_name='LMS No')),
                ('opportunityno', models.IntegerField(unique=True, verbose_name='Opportunity No')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('employeejobtitle', models.CharField(max_length=100, null=True, verbose_name='Job Title')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('authorized', models.CharField(blank=True, max_length=100, null=True, verbose_name='Authorized Person')),
                ('totalnrc', models.IntegerField(verbose_name='Total NRC')),
                ('totalmrc', models.IntegerField(verbose_name='Total MRC')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordinates')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_opportunities', to='crmapp.customer', verbose_name='Customer')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Sales Man')),
                ('status', models.ForeignKey(blank=True, default=crmapp.models.defaultstatus, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_opportunities', to='crmapp.operationstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Opportunitys',
                'verbose_name': 'Opportunity',
            },
        ),
        migrations.CreateModel(
            name='servicecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecategoryname', models.CharField(max_length=100, null=True, verbose_name='Service Category')),
            ],
            options={
                'verbose_name_plural': 'Service Categorys',
                'verbose_name': 'Service Category',
            },
        ),
        migrations.CreateModel(
            name='stcstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stcstatusname', models.CharField(max_length=100, null=True, verbose_name='STC Status')),
            ],
            options={
                'verbose_name_plural': 'STC Status',
                'verbose_name': 'STC Status',
            },
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesttext', models.TextField(null=True, unique=True, verbose_name='Request')),
                ('completion', models.BooleanField(default=False)),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suggestions',
                'verbose_name': 'Suggesion',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name Of Staff')),
                ('staff_id', models.IntegerField(unique=True, verbose_name='Staff_ID')),
                ('joindate', models.DateField(blank=True, null=True, verbose_name='Join Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('employeejobtitle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtitle_staff', to='crmapp.jobtitle', verbose_name='Job Title')),
                ('employeestatus', models.ForeignKey(blank=True, default=crmapp.models.defaulemployeetstatus, on_delete=django.db.models.deletion.CASCADE, related_name='employeestatus_staff', to='crmapp.employeestatus', verbose_name='Employee Status')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'verbose_name': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100, null=True, verbose_name='Service')),
                ('ncc_id', models.IntegerField(unique=True)),
                ('catalogue_id', models.IntegerField(unique=True)),
                ('nrc', models.IntegerField()),
                ('mrc', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('servicecategory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_services', to='crmapp.servicecategory', verbose_name='Service Category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealcategory', models.CharField(choices=[('n', 'New'), ('u', 'Upgrade'), ('d', 'Downgrade')], max_length=1, verbose_name='Deal Category')),
                ('orderno', models.IntegerField(unique=True, verbose_name='Order No')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('accountno', models.IntegerField(verbose_name='Account No')),
                ('servicecategory', models.CharField(max_length=100, null=True, verbose_name='Service Category')),
                ('nrc', models.IntegerField(verbose_name='NRC')),
                ('mrc', models.IntegerField(verbose_name='MRC')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('activationdate', models.DateField(blank=True, null=True, verbose_name='Activation Date')),
                ('cabinetno', models.CharField(max_length=100, null=True, verbose_name='Cabinet No')),
                ('circuitno', models.CharField(max_length=100, null=True, verbose_name='Circuit No')),
                ('addservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addservices_orders', to='crmapp.addservices', verbose_name='Services')),
                ('operationexecutive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_orders', to=settings.AUTH_USER_MODEL, verbose_name='Operation Executive')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_orders', to='crmapp.opportunity', verbose_name='Opportunity')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='crmapp.service', verbose_name='Service')),
                ('status', models.ForeignKey(blank=True, default=crmapp.models.defaultstatusorder, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_orders', to='crmapp.operationstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'verbose_name': 'Order',
            },
        ),
        migrations.AddField(
            model_name='addservices',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_addservices', to='crmapp.opportunity', verbose_name='Opportunity'),
        ),
        migrations.AddField(
            model_name='addservices',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_opportunities', to='crmapp.service', verbose_name='Service'),
        ),
    ]
