# Generated by Django 2.2.13 on 2020-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dealcategory',
            field=models.CharField(choices=[('n', 'New'), ('u', 'Upgrade'), ('d', 'Downgrade')], default='New', max_length=1, verbose_name='Deal Category'),
        ),
    ]
