# Generated by Django 2.2.13 on 2020-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='totalmrc',
            field=models.IntegerField(default=0, verbose_name='Total MRC'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='totalnrc',
            field=models.IntegerField(default=0, verbose_name='Total NRC'),
        ),
    ]
