# Generated by Django 2.2.13 on 2020-12-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20201222_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='crmapp.service', verbose_name='Service'),
        ),
    ]
