# Generated by Django 2.2.13 on 2020-09-03 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0002_auto_20200903_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addservices',
            options={'verbose_name': 'Add Service', 'verbose_name_plural': 'Add Services'},
        ),
        migrations.AddField(
            model_name='addservices',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addservices',
            name='servicecategory',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Category'),
        ),
        migrations.AddField(
            model_name='addservices',
            name='serviceowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman_addservices', to=settings.AUTH_USER_MODEL, verbose_name='Service Owner'),
        ),
        migrations.AddField(
            model_name='addservices',
            name='totalmrc',
            field=models.IntegerField(default=0, verbose_name='Total MRC'),
        ),
        migrations.AddField(
            model_name='addservices',
            name='totalnrc',
            field=models.IntegerField(default=0, verbose_name='Total NRC'),
        ),
        migrations.AddField(
            model_name='addservices',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
    ]
