# Generated by Django 2.2.13 on 2020-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_auto_20200903_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservices',
            name='createdservices',
            field=models.IntegerField(default=0, verbose_name='Created Services'),
        ),
    ]
