# Generated by Django 2.2.13 on 2020-09-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_addservices_createdservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='employeejobtitle',
            field=models.CharField(default='Sales Executive', max_length=100, null=True, verbose_name='Job Title'),
        ),
    ]
