# Generated by Django 2.2.13 on 2020-12-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_remove_order_mrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mrc',
            field=models.IntegerField(default=0, verbose_name='MRC'),
            preserve_default=False,
        ),
    ]
