# Generated by Django 2.2.13 on 2020-09-08 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_auto_20200907_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 19, 53, 7, 685721, tzinfo=utc), verbose_name='Creation Date'),
        ),
    ]
