# Generated by Django 2.2.13 on 2020-09-09 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_auto_20200908_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='granite',
            field=models.CharField(max_length=100, null=True, verbose_name='Granite'),
        ),
        migrations.AddField(
            model_name='order',
            name='imei',
            field=models.IntegerField(blank=True, null=True, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='order',
            name='serviceno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Service No'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 7, 44, 34, 400907, tzinfo=utc), verbose_name='Creation Date'),
        ),
    ]
