# Generated by Django 2.2.13 on 2020-12-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_order_discountmrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='revenue1',
            field=models.IntegerField(default=0, verbose_name='Revenue Before Post'),
        ),
    ]
