# Generated by Django 2.2.13 on 2020-09-16 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_auto_20200909_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('open', 'Open'), ('held', 'Held'), ('finger', 'FingerPrint'), ('post', 'Post'), ('cancel', 'Cancel')], default='open', max_length=12, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 2, 38, 28, 430975, tzinfo=utc), verbose_name='Creation Date'),
        ),
    ]
