# Generated by Django 2.2.13 on 2020-12-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_opportunity_revenue1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revenue2',
            field=models.IntegerField(default=0, verbose_name='Revenue Before Post'),
        ),
        migrations.AddField(
            model_name='order',
            name='revenuep',
            field=models.IntegerField(default=0, verbose_name='Post Revenue'),
        ),
    ]
