# Generated by Django 2.2.13 on 2021-01-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_auto_20201230_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderdate',
            field=models.DateField(blank=True, null=True, verbose_name='Open Date'),
        ),
    ]
