# Generated by Django 2.2.13 on 2020-09-16 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_auto_20200916_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 7, 13, 49, 613274, tzinfo=utc), verbose_name='Creation Date'),
        ),
    ]
