# Generated by Django 2.2.13 on 2021-01-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_order_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunitydate',
            field=models.DateField(blank=True, null=True, verbose_name='Open Date'),
        ),
    ]
