# Generated by Django 2.2.13 on 2020-09-16 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_auto_20200916_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_opportunities', to='crmapp.leadsource', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 7, 54, 31, 271731, tzinfo=utc), verbose_name='Creation Date'),
        ),
    ]
