# Generated by Django 2.2.13 on 2021-01-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_opportunity_opportunitydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_customers', to='crmapp.leadsource', verbose_name='Source'),
        ),
    ]
