# Generated by Django 2.2.13 on 2021-01-11 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0013_customer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assignedto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignedcustomers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
    ]
