# Generated by Django 2.2.13 on 2021-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_customer_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
