# Generated by Django 2.2.13 on 2021-01-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_auto_20210120_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issuedbills',
            field=models.FloatField(default=0, verbose_name='الفواتير الصادرة'),
        ),
        migrations.AddField(
            model_name='order',
            name='paidbills',
            field=models.FloatField(default=0, verbose_name='الفواتير المدفوعة'),
        ),
    ]
