# Generated by Django 2.2.13 on 2021-02-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_auto_20210128_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='ordersmrc',
            field=models.IntegerField(default=0, verbose_name='Orders MRC'),
        ),
    ]
