# Generated by Django 2.2.13 on 2021-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_opportunity_ordersmrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnername', models.CharField(max_length=50, verbose_name='Partner')),
                ('contractstart', models.DateTimeField(verbose_name='Contract Start Date')),
                ('contractend', models.DateTimeField(verbose_name='Contract End Date')),
                ('contractstatus', models.BooleanField(verbose_name='Status')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
    ]
