# Generated by Django 2.2.13 on 2021-02-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_auto_20210216_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='serviceout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_orderout', to='crmapp.service', verbose_name='Service out'),
        ),
    ]
