# Generated by Django 2.2.13 on 2021-02-24 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0020_auto_20210216_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='opportunitynotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_opportunitynotes', to=settings.AUTH_USER_MODEL, verbose_name='Note Owner')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_notes', to='crmapp.opportunity', verbose_name='Opportunity')),
            ],
        ),
    ]
