# Generated by Django 2.2.13 on 2021-03-10 16:14

import crmapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0021_opportunitynotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='fservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100, null=True, verbose_name='Service')),
                ('nrc', models.IntegerField()),
                ('mrc', models.IntegerField()),
                ('commission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fastdatad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealno', models.IntegerField(unique=True, verbose_name='Deal No')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('noofservices', models.IntegerField(default=1, verbose_name='No Of Services')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('totalnrc', models.IntegerField(default=0, verbose_name='Total NRC')),
                ('totalmrc', models.IntegerField(default=0, verbose_name='Total MRC')),
                ('revenue1', models.IntegerField(default=0, verbose_name='Revenue Before Post')),
                ('revenuep', models.IntegerField(default=0, verbose_name='Post Revenue')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordinates')),
                ('expectedclosingdate', models.DateField(blank=True, null=True, verbose_name='Expected Closing Date')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_deals', to=settings.AUTH_USER_MODEL, verbose_name='Broker')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deals', to=settings.AUTH_USER_MODEL, verbose_name='Note Owner')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_deals', to='crmapp.customer', verbose_name='Customer')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fservice_deals', to='crmapp.fservice', verbose_name='Service')),
                ('status', models.ForeignKey(blank=True, default=crmapp.models.defaultstatus, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_deals', to='crmapp.operationstatus', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='dealnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_dealnotes', to=settings.AUTH_USER_MODEL, verbose_name='Note Owner')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_notes', to='crmapp.fastdatad', verbose_name='Deal')),
            ],
        ),
    ]
