# Generated by Django 2.2.13 on 2021-03-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0022_dealnotes_fastdatad_fservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastdatad',
            name='brokercommission',
            field=models.IntegerField(default=0, verbose_name='Commission'),
        ),
        migrations.AddField(
            model_name='fastdatad',
            name='commissiontype',
            field=models.CharField(choices=[('onetime', 'onetimen'), ('monthly', 'monthly')], default='', max_length=20, verbose_name='Commissionype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastdatad',
            name='ourcommission',
            field=models.IntegerField(default=0, verbose_name='Commission'),
        ),
    ]
