# Generated by Django 2.2.13 on 2021-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0023_auto_20210311_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastdatad',
            name='activationdate',
            field=models.DateField(blank=True, null=True, verbose_name='Activation Date'),
        ),
        migrations.AlterField(
            model_name='fservice',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fservice',
            name='mrc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fservice',
            name='nrc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fservice',
            name='servicename',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Service'),
        ),
    ]
