# Generated by Django 2.2.13 on 2021-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0024_auto_20210311_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastdatad',
            name='cancellationdate',
            field=models.DateField(blank=True, null=True, verbose_name='Cancellation Date'),
        ),
    ]
