# Generated by Django 2.2.13 on 2021-03-23 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0025_fastdatad_cancellationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100, null=True, verbose_name='Customer Name')),
                ('cr', models.IntegerField(blank=True, null=True, unique=True)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fcustomers', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
