# Generated by Django 2.2.13 on 2021-03-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0026_fcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastdatad',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcustomer_deals', to='crmapp.fcustomer', verbose_name='Customer'),
        ),
    ]
