# Generated by Django 2.2.13 on 2021-04-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0027_auto_20210323_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='finvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.IntegerField(unique=True, verbose_name='Invoice No')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('Year', models.IntegerField(verbose_name='Year')),
                ('Month', models.IntegerField(verbose_name='Month')),
                ('Value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Value')),
                ('Paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('recievedamount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Recieved Amount')),
                ('remainingamount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Remaining Amount')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('customername',)},
        ),
        migrations.AlterField(
            model_name='fastdatad',
            name='brokercommission',
            field=models.IntegerField(default=0, verbose_name='Broker Commission'),
        ),
        migrations.AlterField(
            model_name='fastdatad',
            name='commissiontype',
            field=models.CharField(choices=[('onetime', 'onetime'), ('monthly', 'monthly')], max_length=20, verbose_name='Commissionype'),
        ),
        migrations.AlterField(
            model_name='fastdatad',
            name='ourcommission',
            field=models.IntegerField(default=0, verbose_name='Company Commission'),
        ),
        migrations.CreateModel(
            name='fpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('paymentdate', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Payment')),
                ('invoiceno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='crmapp.finvoice', verbose_name='Invoice No')),
            ],
        ),
        migrations.CreateModel(
            name='finvoiceitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_invoiceitems', to='crmapp.fastdatad', verbose_name='Deal')),
                ('invoiceno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='crmapp.finvoice', verbose_name='Invoice No')),
            ],
        ),
    ]
