# Generated by Django 2.2.13 on 2021-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0028_auto_20210401_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finvoice',
            old_name='Month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='finvoice',
            old_name='Paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='finvoice',
            old_name='Value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='finvoice',
            old_name='Year',
            new_name='year',
        ),
    ]
