# Generated by Django 2.2.13 on 2021-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0031_auto_20210401_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='finvoice',
            name='datescore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
