# Generated by Django 2.2.13 on 2021-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0032_finvoice_datescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastdatad',
            name='datescore',
            field=models.IntegerField(default=0),
        ),
    ]
