# Generated by Django 2.2.13 on 2021-04-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0034_finvoiceitem_itemvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finvoice',
            name='datescore',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
