# Generated by Django 2.2.13 on 2021-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0035_auto_20210402_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastdatad',
            name='referenceno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference No'),
        ),
    ]
