# Generated by Django 2.2.13 on 2021-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0036_fastdatad_referenceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastdatad',
            name='activationdate1',
            field=models.DateField(blank=True, null=True, verbose_name='Activation Date'),
        ),
    ]
