# Generated by Django 2.2.13 on 2021-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0037_fastdatad_activationdate1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.IntegerField(default=0, verbose_name='Commission'),
        ),
    ]
