# Generated by Django 2.2.13 on 2021-04-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0039_order_activationdate1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.FloatField(default=0, verbose_name='Commission'),
        ),
    ]
