# Generated by Django 2.2.13 on 2021-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0040_auto_20210410_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Commission'),
        ),
    ]
