# Generated by Django 2.2.13 on 2021-05-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0042_auto_20210421_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finvoice',
            name='recievedamount',
            field=models.IntegerField(default=0, verbose_name='Recieved Amount'),
        ),
        migrations.AlterField(
            model_name='finvoice',
            name='remainingamount',
            field=models.IntegerField(default=0, verbose_name='Remaining Amount'),
        ),
        migrations.AlterField(
            model_name='finvoice',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='finvoiceitem',
            name='itemvalue',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='fpayment',
            name='payment',
            field=models.IntegerField(verbose_name='Payment'),
        ),
    ]
