# Generated by Django 2.2.13 on 2021-05-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0043_auto_20210501_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.IntegerField(default=0, verbose_name='Account No')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('nooforders', models.IntegerField(default=0, verbose_name='No of orders')),
                ('noofbills', models.IntegerField(default=0, verbose_name='No of bills')),
                ('billsvalue', models.IntegerField(default=0, verbose_name='Value')),
                ('paymentdate', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment', models.IntegerField(verbose_name='Payment')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
