# Generated by Django 2.2.13 on 2021-05-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0044_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='Payment'),
        ),
    ]
