# Generated by Django 2.2.13 on 2021-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0045_auto_20210503_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='noofpostorders',
            field=models.IntegerField(default=0, verbose_name='No of orders'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stccommissionrecieved',
            field=models.BooleanField(default=False, verbose_name='STC Recieved Commission '),
        ),
        migrations.AlterField(
            model_name='order',
            name='stccommissionreport',
            field=models.BooleanField(default=False, verbose_name='STC Commission  Report'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stcpostreport',
            field=models.BooleanField(default=False, verbose_name='STC Post Report'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stcsalesreport',
            field=models.BooleanField(default=False, verbose_name='STC Sales Report'),
        ),
    ]
