# Generated by Django 2.2.13 on 2021-06-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0047_accounts_activationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastdatad',
            name='netcommission',
            field=models.IntegerField(default=0, verbose_name='Broker Commission'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Net Commission'),
        ),
    ]
