# Generated by Django 2.2.13 on 2021-08-11 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0048_auto_20210630_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=50, null=True, unique=True, verbose_name='Activity')),
            ],
        ),
        migrations.AlterField(
            model_name='fastdatad',
            name='netcommission',
            field=models.IntegerField(default=0, verbose_name='Net Commission'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Commission'),
        ),
        migrations.CreateModel(
            name='activityrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_activities', to='crmapp.activity', verbose_name='Activity')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL, verbose_name='Note Owner')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_activities', to='crmapp.customer', verbose_name='Customer')),
            ],
        ),
    ]
