# Generated by Django 2.2.13 on 2021-08-22 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0050_company_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderimport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=20, verbose_name='Order No')),
                ('accountno', models.IntegerField(verbose_name='Account No')),
                ('serviceno', models.IntegerField(blank=True, null=True, verbose_name='Service No')),
                ('product', models.CharField(max_length=40, verbose_name='Order No')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.99)], verbose_name='Discount')),
            ],
        ),
    ]
