# Generated by Django 2.2.13 on 2021-10-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0052_accounts_ispayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimport',
            name='myday',
            field=models.IntegerField(default=1, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='orderimport',
            name='mymonth',
            field=models.IntegerField(default=1, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='orderimport',
            name='myyear',
            field=models.IntegerField(default=2000, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='orderimport',
            name='product',
            field=models.CharField(max_length=40, verbose_name='Product'),
        ),
    ]
