# Generated by Django 2.2.13 on 2022-07-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='thejobtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle_name', models.CharField(max_length=100, unique=True, verbose_name='Project Name')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('Central', 'Central'), ('Western', 'Western'), ('Eastern', 'Eastern')], max_length=20, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobtitle_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtitle_profile', to='accounts.thejobtitle'),
        ),
    ]
